# Site settings
title: gabriela scardine | developer
description: Gabi's personal website
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site

# Owner/author information
owner:
  email: gabrielascardine@gmail.com
  github:  gabiiz
  linkedin: gabrielascardine
  tumblr: 
  twitter: 

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


gems: [jekyll-paginate]