# Site settings
title: gabriela scardine | developer
description: "Gabriela Scardine, software developer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://gscardine.github.io # the base hostname & protocol for your site

# Owner/author information
owner:
  email: gabrielascardine@gmail.com
  github:  gscardine
  linkedin: gabrielascardine
  tumblr: 
  twitter: 

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/


gems: [jekyll-paginate]